/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ipc2.analizador.UI.Paneles;

import java.util.List;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos117
 */
public class ReportesSintactico extends javax.swing.JPanel {

  
    public static JButton button;

    /**
     * Creates new form Reportes
     */
    public ReportesSintactico() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Tokens", "Bloque", "Cantidad Func o Metd", "Cantidad de llamadas ", "Fila", "Columna", "Parametros de Funcion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    public void insertarInfo(List<List<Object>> listOfLists){
        jTable1.removeAll();
        jTable1.repaint();
        
        System.out.println("lista de listas carga : " + listOfLists);
        
        DefaultTableModel tableModel = new DefaultTableModel(
        new Object[][] {},
        new String[] {"Tipo", "Tokens", "Bloque","Cantidad Fucn o Metd","Cantidad de llamadas ", "Fila", "Columna", "Parametros de funcion"}
        );

        for (List<Object> list : listOfLists) {
            
            Object tipo = list.get(1); 
            Object tokens = list.get(0);
            Object Bloque = list.get(list.size()-1);
            Object Fila = null;
            Object Columna = null;
            
            
// Obtener el valor para la columna "Tipo"
            tableModel.addRow(new Object[]{tipo, tokens, Bloque, null, null, Fila, Columna, null});
            
            
        }
        
        SwingUtilities.invokeLater(() -> {
            jTable1.setModel(tableModel);
            tableModel.fireTableDataChanged();
        });
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
